# Generated by Django 5.1.4 on 2025-01-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_recipe', to='recipes.recipes')),
                ('similar_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_recipe', to='recipes.recipes')),
            ],
        ),
    ]
