# Generated by Django 5.1.4 on 2024-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('servings', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('dificulty', models.CharField(max_length=255)),
                ('valoration', models.FloatField()),
            ],
        ),
    ]
