# Generated by Django 5.1.4 on 2024-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ingredientes', models.TextField()),
                ('accesorios', models.TextField()),
                ('tiempo_total', models.IntegerField()),
                ('tiempo_preparacion', models.IntegerField()),
                ('tiempo_de_coccion', models.IntegerField()),
                ('tiempo_de_resposo', models.IntegerField()),
                ('num_personas', models.IntegerField()),
            ],
        ),
    ]
