# Generated by Django 5.1.2 on 2024-12-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='introduccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_coccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
