# Generated by Django 5.1.2 on 2024-12-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_receta_autor_receta_categoria_receta_introduccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='visitas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
