# Generated by Django 5.1.2 on 2024-12-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_receta_titulo_alter_receta_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
